# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Szymon Bartoszewicz
title: Computer Science student
email: simon-ba@outlook.com
# website: www.avalanche284.github.io/simon-ba/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: sibartos
github_username:  avalanche284
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: sibartos
linkedin_username: szymonbartoszewicz
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey, my name's Szymon and I'm a Computer Science student. I have 13+ months of experience of troubleshooting Windows & network at Service Desk gaining teamwork & problem-solving skills.
  Live in Poland, willing to relocate. Also, open to remote work opportunities.

  Currently I learn <mark>Python</mark> and write my thesis which is connected with <mark>Data Science</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: CleanAirTrip Python application
        link: https://github.com/avalanche284/CleanAirTrip
        # link_text: Project Website
        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Take a deep breath of a clean air and travel around the world.
        description: | # this will include new lines to allow paragraphs
          This is my final project application of Harvardâ€™s CS50 course: Introduction to Programming with <mark>Python</mark>. It is a simple, command-line interface application program.
      - layout: top-middle
        title: TrueNAS 12 Server
        link: https://www.linkedin.com/feed/update/urn:li:activity:6815917883260968960/?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A6815917883260968960%29
        # link_text: Project Website
        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>networking</mark>. I have always wanted to have a NAS server up and running by myself. After a course at the University I bought necessary componenets, built the computer and set up the NAS. After that I was also using it as a machine to virtualize systems as the TrueNAS OS has this capability.
      - layout: top-middle
        title: Hackintosh â˜ ï¸ðŸŽðŸ’»
        link: https://www.linkedin.com/feed/update/urn:li:activity:6770245686622486528/
        # link_text: Project Website
        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Always wanted to have a Mac but could not afford to buy one so I built one!
        description: | # this will include new lines to allow paragraphs
          Started working on it as my dream o having Apple machine. Inspired by a friend of mine I bought necessary additions to my old computer, read a lot of threads on specific forums finally I managed to set up up and running Hackintosh. Not all things we working obviously but this experience gave me an incredible fun by fixing errors that were coming while working on it.
          Through this yourney I learned basics of working using <mark>Bash</mark> and <mark>CMD</mark>.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Pavia, Pavia, Italy
        caption: 2022 - 2023
        sub_title: Master of Science, MSc in Computer Science
        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Being qualified to take part in Erasmus student exchange programme I started studying Computer Engineering, Data Science, at University of Pavia in Italy.

      - layout: left
        title: WSB University, Gdansk, Poland
        caption: 2021 - 2023
        sub_title: Master of Science, MSc in Computer Science
        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Last year I started studying at WSB University in Gdansk. Since then I gained a knowledge and experience in working using <mark>Git</mark>. I also got to know basics of statics and <mark>data analysis</mark> in <mark>R</mark>. When it comes to system administration I am familiar with <mark>Bash</mark> and <mark>Linux</mark>. I also got to know basics of <mark>Docker</mark> on <mark>virtual machines</mark> and <mark>IoT</mark> by setting up HomeAssistant. Basics of <mark>Apache Web Server</mark> are also known to me.
          By attending additinal classes I got to know how it is to work in <mark>Agile</mark>.

      - layout: left
        title: Gdynia Maritime University, Gdynia, Poland
        caption: 2018 - 2021
        sub_title: Bachelor of Arts, B.A. in Economic and Finance
        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          At Gdynia Maritime University I oppose of gaining experience in collaboration with other students and flatmates I was training skills in <mark>HTML</mark> with <mark>CMSs</mark>. Using Excel we solved problems using VSLOOKUP, pivot tables and IFs.
          On the 3rd year I started learnig <mark>AWS</mark> and after a couple of months I got certificate Certified Cloud Practitioner.
          On additional classes I started learning about <mark>networks</mark> where we gained skills on programme "Introduction to networks" by Cisco.

#          I spent of my  time as a committee member of the *Logistics Club* but I did not find it interersting ot me taking on roles such as *Trip Secretary* and *Vice-President*.
      - layout: left
        title: I LO (High School), Suwalki, Poland
        caption: 2015 - 2018
        sub_title: Mathematics, Computer Science
        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          In my High School I got to know basic <mark>C++</mark> programming, HTML & CSS and Excel functions as
          During that time I devoted a lot of time <mark>making movies</mark> that was promoting the high school (which you can watch in Project section on this site)

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fujitsu Technology Solutions
        link: https://www.fujitsu.com/pl/
        # link_text: https://www.fujitsu.com/pl/
        sub_title: Service Desk Expert EUC 2nd Line
        caption: February 2022 - September 2022
        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Managing <mark>AD</mark> & O365 accounts in magnificent way for more than 4000 employees; accelerated & automated a process for creating new accounts by 37%
            - Handling services in <mark>Microsoft O365 Admin Centre</mark>: share-boxes, distribution lists, Teams, OneDrive, SharePoint; installing software via <mark>SCCM</mark>, realizing tickets in required SLA taking care of user satisfaction
            - Communicating thoroughly with IT operations managers, service process controllers, service delivery directors and team members, effectively reporting of scripts and users issues to assure customer satisfaction
            - Awarded Fujitsuâ€™s <mark>STARS Bronze Award</mark> â€œIn recognition of very fast stepping into the new roleâ€
      - layout: left
        title: Aplitt Sp. z o.o.
        link: https://aplitt.pl
        # link_text: https://aplitt.pl
        sub_title: Service Desk Agent
        caption: July 2021 - January 2022
        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Provided excellent phone-, remote desktop-, and chat-based support to more that 1000 users, including troubleshooting, diagnosing and resolving network-, software-, and hardware-related issues
            - Handled incidents, requests, ITIL Service Management Processes with emphasis on Incident, Request Fulfillment, Change, and Knowledge Management improving customer satisfaction
            - Responded and monitor calls to the direct response line for immediate assistance to customers
            - Recognized for superior contribution in dealing with everyday duties also being thorough and reliable in the role





#      Look at this cool image
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
